---
# This automation simulates the use of the IKEA TRADFRI Dimmer control
# connected through Z2MQTT.

# | Button      | Action              |
# | ----------- | ------------------- |
# | on (short)  | Turn the light on   |
# | off (short) | Turn the light off  |
# | on (long)   | Increase brightness |
# | off (long)  | Decrease brightness |

blueprint:
  source_url: https://github.com/thikade/homeassistant-blueprints/blob/main/switches/ikea_tradfri_2button_remote_brightness.yaml

  name: IKEA TRADFRI - 2 Button Remote - OnOff and Brightness

  description: >-
    This automation implements the use of the IKEA TRADFRI 2-gang on/off dimmer-switch
    connected through Z2M.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: "Select the remote control you wish to use (sensor)"
      selector:
        device:
          entity:
            - domain: sensor
          filter:
            - manufacturer: IKEA
              # model: TRADFRI 2-gang on/off switch
    light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          filter:
            - domain: light
    speed:
      name: Speed
      description: The speed in which to update the light when the button is held.
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          unit_of_measurement: milliseconds
          mode: slider
      default: 500

mode: restart
max_exceeded: silent

variables:
  var_speed: !input speed

trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input remote

action:
  - choose:
      # Short-Press the on button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.old_state.state == "on" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness: 254
              # hs_color:
              #  - 38.222
              #  - 52.941
              # transition: "{{ (var_speed / 1000)|float }}"

      # Long-Press the on button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light
                  data:
                    brightness_step_pct: 10
                    transition: "{{ (var_speed / 1000)|float }}"
                - delay:
                    milliseconds: !input speed

      # Short-Press the off button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.old_state.state == "off" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light
            # data:
            #   transition: "{{ (var_speed / 1000)|float }}"

      # Long-Press the off button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light
                  data:
                    brightness_step_pct: -10
                    transition: "{{ (var_speed / 1000)|float }}"
                - delay:
                    milliseconds: !input speed

    default:
      - action: notify.pushover
        data:
          title: "Title"
          message: |
            Message
            {{ trigger.event.data | default('trigger N/A') }}
          # target:
          #   - iphoneXV
          data:
            sound: pianobar
            priority: 0

